---
- name: add SSH inbound rule to Panorama device group
  panos_security_rule:
    ip_address: "192.168.1.85"
    username: "{{ panos_username }}"
    password: "{{ panos_password }}"
    device_group: 'Cloud Edge'
    rule_name: 'SSH permit'
    description: 'SSH rule test'
#    tag_name: ['production']
    source_zone: ['any']
    source_ip: ['any']
    destination_zone: ['any']
    destination_ip: ['1.1.1.1']
    application: ['ssh']
    action: 'allow'
    commit: no